services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"  # maps host port 3307 to MySQL in the container
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
